[package]
name = "oc-http"
version = "0.1.0"
authors = ["Your Name <over.codes@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
httparse = "1.3.4"
async-std = "1.8.0"
log = "0.4"
regex = "1"
async-trait = "0.1.42"